# fly.toml app configuration file generated for vrcca on 2024-05-26T17:38:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vrcca'
primary_region = 'ams'


[env]
  SMOKE_TEST_PORT = '4040'

[[vm]]
  size = 'shared-cpu-1x'

[[services]]
  internal_port = 4040
  protocol = "tcp"

  [[services.ports]]
    port = "4040"
